### ISSUE TITLE
Does not work with Python 3

### ISSUE THREAD

**Issue by doragasu** [pandysong/dxf2kicad_mod#2]
Traceback:

```jalon dxf2kicad_mod $ python dxf2kicad_mod.py test_data.dxf > /tmp/test.kicad_mod
Traceback (most recent call last):
  File "/tmp/dxf2kicad_mod/dxf2kicad_mod.py", line 10, in <module>
    import kicad_mod_format as kf
  File "/tmp/dxf2kicad_mod/kicad_mod_format.py", line 76, in <module>
    exec('{} = functools.partial(Cmd, "{}")'.format(c, c))
  File "<string>", line 1, in <module>
NameError: name 'functools' is not defined```

**Comment by axibo-reiner** [comment]
This does work with python3 just add. 

```python
import functools
```
to the top of `dxf2kicad_mod.py`
